#oauth2
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 595137599284-2i1g8tpn9cooh0b4h2aevem4g059vohr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: AAnEIsBV1xfjQ3KeUYZI
            client-secret: Vk8R_MBlQn
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope : name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response





